spring:

  application:
    name: SpringAI

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ai
    driver-class-name: org.postgresql.Driver
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
#      chat:
#        options:
#          temperature: 0.2
#          model: "gpt-3.5-turbo"
#          max-tokens: 100

  jwt:
    secret: ${JWT_SECRET}