spring:
  application:
    name: SpringAI

  datasource:
      url: jdbc:postgresql://localhost:5432/ai_you
      driver-class-name: org.postgresql.Driver
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:secret-key}
      chat:
        options:
          model: "gpt-4o"
      embedding:
        options:
          model: "text-embedding-3-small"
  jwt:
    secret: ${JWT_SECRET:This_is_a_secret_key_with_length_greater_than_256_bits}
